### ISSUE TITLE
RFID Reader Help 

### ISSUE THREAD

**Issue by TWR2020** [MXET/SCUTTLE#44]
We are trying to use the RFID reader and are not sure what we are doing wrong. We wired the device as shown in the diagram and followed the code setup from the L1_rfid.py file. We then tried to write and read a tag however it does not appear to work and wanted to ask for advice. Below are samples of the code we ran.Thank you  

**Sample of the Setup code**
`debian@scuttle:~$ git clone https://github.com/ansarid/MFRC522-python
fatal: destination path 'MFRC522-python' already exists and is not an empty directory.
debian@scuttle:~$ cd MFRC522-python
debian@scuttle:~/MFRC522-python$ sudo python3 setup.py install
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing dependency_links to mfrc522.egg-info/dependency_links.txt
writing mfrc522.egg-info/PKG-INFO
writing requirements to mfrc522.egg-info/requires.txt
writing top-level names to mfrc522.egg-info/top_level.txt
reading manifest file 'mfrc522.egg-info/SOURCES.txt'
writing manifest file 'mfrc522.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/mfrc522
copying build/lib/mfrc522/MFRC522.py -> build/bdist.linux-armv7l/egg/mfrc522
copying build/lib/mfrc522/__init__.py -> build/bdist.linux-armv7l/egg/mfrc522
copying build/lib/mfrc522/SimpleMFRC522.py -> build/bdist.linux-armv7l/egg/mfrc522
byte-compiling build/bdist.linux-armv7l/egg/mfrc522/MFRC522.py to MFRC522.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/mfrc522/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/mfrc522/SimpleMFRC522.py to SimpleMFRC522.cpython-35.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying mfrc522.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying mfrc522.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying mfrc522.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying mfrc522.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying mfrc522.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/mfrc522-0.0.7-py3.5.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing mfrc522-0.0.7-py3.5.egg
Removing /usr/local/lib/python3.5/dist-packages/mfrc522-0.0.7-py3.5.egg
Copying mfrc522-0.0.7-py3.5.egg to /usr/local/lib/python3.5/dist-packages
mfrc522 0.0.7 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.5/dist-packages/mfrc522-0.0.7-py3.5.egg
Processing dependencies for mfrc522==0.0.7
Searching for spidev==3.4
Best match: spidev 3.4
Processing spidev-3.4-py3.5-linux-armv7l.egg
spidev 3.4 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/spidev-3.4-py3.5-linux-armv7l.egg
Finished processing dependencies for mfrc522==0.0.7`

**Sample of trying to write** 
`debian@scuttle:~/basics$ sudo python3 L1_rfid.py
Place RFID on RFID writer.
^CTraceback (most recent call last):
  File "L1_rfid.py", line 33, in <module>
    write_rfid("Hello World!")  # Write "Hello World!" to RFID
  File "L1_rfid.py", line 16, in write_rfid
    reader.write(text)          # Write data to RFID
  File "/usr/local/lib/python3.5/dist-packages/mfrc522-0.0.7-py3.5.egg/mfrc522/SimpleMFRC522.py", line 92, in write
  File "/usr/local/lib/python3.5/dist-packages/mfrc522-0.0.7-py3.5.egg/mfrc522/SimpleMFRC522.py", line 96, in write_no_block
  File "/usr/local/lib/python3.5/dist-packages/mfrc522-0.0.7-py3.5.egg/mfrc522/MFRC522.py", line 260, in MFRC522_Request
  File "/usr/local/lib/python3.5/dist-packages/mfrc522-0.0.7-py3.5.egg/mfrc522/MFRC522.py", line 206, in MFRC522_ToCard
  File "/usr/local/lib/python3.5/dist-packages/mfrc522-0.0.7-py3.5.egg/mfrc522/MFRC522.py", line 160, in Write_MFRC522
KeyboardInterrupt`

**Sample of trying to read**
`debian@scuttle:~/basics$ sudo python3 L1_rfid.py
^CTraceback (most recent call last):
  File "L1_rfid.py", line 24, in <module>
    sn, data = read_rfid()  # Read card serial number and data and store to sn and data variables
  File "L1_rfid.py", line 12, in read_rfid
    id, text = reader.read()    # Read RFID Serial Number and Data
  File "/usr/local/lib/python3.5/dist-packages/mfrc522-0.0.7-py3.5.egg/mfrc522/SimpleMFRC522.py", line 42, in read
  File "/usr/local/lib/python3.5/dist-packages/mfrc522-0.0.7-py3.5.egg/mfrc522/SimpleMFRC522.py", line 65, in read_no_block
  File "/usr/local/lib/python3.5/dist-packages/mfrc522-0.0.7-py3.5.egg/mfrc522/MFRC522.py", line 260, in MFRC522_Request
  File "/usr/local/lib/python3.5/dist-packages/mfrc522-0.0.7-py3.5.egg/mfrc522/MFRC522.py", line 223, in MFRC522_ToCard
  File "/usr/local/lib/python3.5/dist-packages/mfrc522-0.0.7-py3.5.egg/mfrc522/MFRC522.py", line 175, in ClearBitMask
  File "/usr/local/lib/python3.5/dist-packages/mfrc522-0.0.7-py3.5.egg/mfrc522/MFRC522.py", line 163, in Read_MFRC522
KeyboardInterrupt`

**Comment by TWR2020** [comment]
Ground pin on the Beaglebone was discovered to be bent during troubleshooting.
