### ISSUE TITLE
Issue using L1_servo.py

### ISSUE THREAD

**Issue by TheWhiteCollarPlayers** [MXET/SCUTTLE#46]
Hardware setup: 
     Beagle Bone Blue connected via 12V barrel jack to wall outlet for power.
     Continuous servo connected in correct wiring configuration to servo1 position on BeagleBone Blue

Software Setup:
     uncommented while loop in L1_servo.py returns the following in the console:
`/usr/local/lib/python3.5/dist-packages/rcpy-0.5.0-py3.5-linux-armv7l.egg/rcpy/__init__.py:116: UserWarning: > Robotics cape initialized
  warnings.warn('> Robotics cape initialized')
/usr/local/lib/python3.5/dist-packages/rcpy-0.5.0-py3.5-linux-armv7l.egg/rcpy/__init__.py:127: UserWarning: > Installing signal handlers
  warnings.warn('> Installing signal handlers')
ERROR: in rc_pru_shared_mem_ptr could not open /dev/mem: Permission denied
Need to be root to access PRU shared memory
ERROR in rc_servo_init, failed to map shared memory pointer
Traceback (most recent call last):
  File "L1_servo.py", line 10, in <module>
    import rcpy.servo as servo
  File "/usr/local/lib/python3.5/dist-packages/rcpy-0.5.0-py3.5-linux-armv7l.egg/rcpy/servo.py", line 2, in <module>
    from rcpy._servo import *
SystemError: initialization of _servo failed without raising an exception
Initiating cleanup...
Done with cleanup`

Troubleshooting steps taken:
    Ran the following command which successfully actuated the servo: `sudo rc_test_servos -s 1.5`
Ran check_installed.sh and let it run to completion, no problems.
Issue persists, assistance required. Thank you.

**Comment by TheWhiteCollarPlayers** [comment]
Solved, needed to run L1 as sudo, now wondering how if I can import into my L2 as sudo?
